//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WristBandAPI.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class sensor_data
    {
        public long id { get; set; }
        public Nullable<long> sensor { get; set; }
        public string data { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public Nullable<short> is_delete { get; set; }
    
        public virtual xxbt_yesno xxbt_yesno { get; set; }
        public virtual sensor_info sensor_info { get; set; }
    }
}
