//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WristBandAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class login_session
    {
        public long id { get; set; }
        public string session_id { get; set; }
        public long user_id { get; set; }
        public System.DateTime start_datetime { get; set; }
        public Nullable<System.DateTime> end_datetime { get; set; }
        public Nullable<short> is_delete { get; set; }
    
        public virtual xxbt_yesno xxbt_yesno { get; set; }
        public virtual user user { get; set; }
    }
}
