//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WristBandAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wristband_masterEntities : DbContext
    {
        public wristband_masterEntities()
            : base("name=wristband_masterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<login_session> login_session { get; set; }
        public virtual DbSet<sensor_data> sensor_data { get; set; }
        public virtual DbSet<sensor_info> sensor_info { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<wristband_info> wristband_info { get; set; }
        public virtual DbSet<xxbt_default> xxbt_default { get; set; }
        public virtual DbSet<xxbt_sensor_type> xxbt_sensor_type { get; set; }
        public virtual DbSet<xxbt_user_type> xxbt_user_type { get; set; }
        public virtual DbSet<xxbt_wb_status> xxbt_wb_status { get; set; }
        public virtual DbSet<xxbt_yesno> xxbt_yesno { get; set; }
    }
}
